Setting up loading button
smileidentity/android pull request #170
Opened 2023-07-20 09:14 UTC by jumaallan

Story: N/

## Summary

Adds a loading button which shows text or a circular loading indicator depending on the state of the app

## Known Issues

Any shortcomings in your work. This may include corner cases not correctly handled or issues related
to but not within the scope of your PR. Design compromises should be discussed here if they were not
already discussed above.

## Test Instructions

Concise test instructions on how to verify that your feature works as intended. This should include
changes to the development environment (if applicable) and all commands needed to run your work.

## Screenshot

If applicable (e.g. UI changes), add screenshots to help explain your work.

![Screenshot 2023-07-20 at 12 07 22 PM](https://github.com/smileidentity/android/assets/25085146/57eb7b28-b143-4f9a-98d4-0d6a345a29e5)

2023-07-20 13:18 UTC, jumaallan commented on lib/src/main/java/com/smileidentity/compose/components/LoadingIndicatorButton.kt
> +    enabled: Boolean = true,
I have removed this in the next PR. If loading, we disable button so no need to pass two params

2023-07-20 16:39 UTC, vanshg requested changes
Can you add a test for this since it's in the SDK?

2023-07-20 16:39 UTC, vanshg commented on lib/src/main/java/com/smileidentity/compose/components/LoadingIndicatorButton.kt
Can you rename the file to match the component name? `LoadingButton.kt`

2023-07-20 16:39 UTC, vanshg commented on lib/src/main/java/com/smileidentity/compose/components/LoadingIndicatorButton.kt
> +fun LoadingIndicatorButtonPreview() {
Same here
```suggestion
fun LoadingButtonPreview() {
```

2023-07-20 16:39 UTC, vanshg commented on lib/src/main/java/com/smileidentity/compose/components/LoadingIndicatorButton.kt
> +    enabled: Boolean = true,
Agreed

2023-07-21 18:26 UTC, vanshg approved these changes

2023-07-21 18:27 UTC, merged