Support Global Doc V
smileidentity/android pull request #200
Opened 2023-08-23 12:52 UTC by jumaallan

Story: https://app.shortcut.com/smileid/story/10425/support-global-docv

## Summary

A few sentences/bullet points about the changes

## Known Issues

Any shortcomings in your work. This may include corner cases not correctly handled or issues related
to but not within the scope of your PR. Design compromises should be discussed here if they were not
already discussed above.

## Test Instructions

Concise test instructions on how to verify that your feature works as intended. This should include
changes to the development environment (if applicable) and all commands needed to run your work.

## Screenshot

If applicable (e.g. UI changes), add screenshots to help explain your work.

2023-08-23 15:43 UTC, vanshg commented on lib/src/main/java/com/smileidentity/compose/SmileIDExt.kt
> +    countryCode: String? = null,
Shouldn't the countryCode be required?

Can you also update the KDocs above?

2023-08-23 15:46 UTC, jumaallan commented on lib/src/main/java/com/smileidentity/compose/SmileIDExt.kt
> +    countryCode: String? = null,
yeah let me fix this

2023-08-23 15:47 UTC, vanshg commented
Can you also update the changelog?

2023-08-28 18:43 UTC, vanshg requested changes
The call to `hasBackSide` should happen _within_ the DocV flow (so that it is abstracted away from partners) rather than as a parameter that is passed in

2023-08-28 18:43 UTC, vanshg commented on lib/src/main/java/com/smileidentity/fragment/DocumentVerificationFragment.kt
> +            documentType: String,
Can you make these 2 the first 2 parameters of the method? Since they are required arguments

2023-08-28 18:43 UTC, vanshg commented on lib/src/main/java/com/smileidentity/fragment/DocumentVerificationFragment.kt
> +private const val KEY_DOCUMENT_TYPE = "documentType"
Can you move this line down to be with the declaration of the documentType extension property?

2023-08-28 18:43 UTC, vanshg commented on lib/src/main/java/com/smileidentity/viewmodel/document/OrchestratedDocumentViewModel.kt
> +                // todo - what happens when we don't pass a document type here?
Shouldn't IdInfo be updated to allow for a null idType? or does it expect an empty string?

2023-08-28 18:43 UTC, vanshg commented on sample/src/main/java/com/smileidentity/sample/compose/DocumentVerificationIdTypeSelector.kt
> +            // onClick = { onIdTypeSelected(selectedCountry!!, selectedIdType) },
Remove commented code

2023-08-28 18:43 UTC, vanshg commented on sample/src/main/java/com/smileidentity/sample/compose/MainScreen.kt
> +                        captureBothSides = it.arguments?.getBoolean("hasBackSide")!!,
I think it may be better to remove this from the interface entirely, now that we have the API endpoint.

Also, it should be the DocV flow that automatically determines whether there is a backside, it shouldn't need to be passed in.

And in the case where only the country code is supplied and we can't check whether this is a back or not, we need to show a skip button on the Document Back Instructions screen

2023-09-14 21:38 UTC, vanshg commented on lib/src/main/java/com/smileidentity/compose/SmileIDExt.kt
>      jobId: String = rememberSaveable { randomJobId() },
while you're here can you change `showInstructions` to default to `true`? (not sure why it was set to false initially)

2023-09-15 16:16 UTC, vanshg commented on lib/src/main/java/com/smileidentity/networking/SmileIDService.kt
> +    suspend fun getGlobalDocVConfig(@Body request: ProductsConfigRequest): GlobalDocVResponse
nit: getValidDocuments

2023-09-18 15:19 UTC, jumaallan commented on lib/src/main/java/com/smileidentity/viewmodel/document/OrchestratedDocumentViewModel.kt
> +                // todo - what happens when we don't pass a document type here?
This is fixed

2023-09-18 15:19 UTC, jumaallan commented on lib/src/main/java/com/smileidentity/fragment/DocumentVerificationFragment.kt
> +private const val KEY_DOCUMENT_TYPE = "documentType"
Done

2023-09-18 15:20 UTC, jumaallan commented
> The call to `hasBackSide` should happen _within_ the DocV flow (so that it is abstracted away from partners) rather than as a parameter that is passed in

As per the last discussion, the call now happens inside the country selection flow, and is passed into the sdk as a parameter. The value is always set to true, so we can show the skip button inside the sdk

2023-09-18 19:02 UTC, vanshg commented on sample/src/main/java/com/smileidentity/sample/viewmodel/IdTypeSelectorAndFieldInputViewModel.kt
> +            // val countryList = servicesResponseForJobType
Let's clean up the commented code

2023-09-18 19:02 UTC, vanshg commented on sample/src/main/java/com/smileidentity/sample/compose/DocumentVerificationIdTypeSelector.kt
> +    onIdTypeSelected: (String, String?, Boolean) -> Unit,
can we give names to these?
`onIdTypeSelected: (countryCode: String, idType: String?, captureBothSides: Boolean) -> Unit,`

2023-09-18 19:05 UTC, vanshg commented on CHANGELOG.md
> +- DocV updated to dynamically shows back of ID capture
```suggestion
- Document Verification updated to dynamically shows back of ID capture 
```

2023-09-18 19:05 UTC, vanshg commented on CHANGELOG.md
> +- Removed `documentType` as a required field in DocV
```suggestion
- Removed `documentType` as a required field in Document Verification
```

2023-09-18 19:05 UTC, vanshg commented on CHANGELOG.md
> +  DocV
```suggestion
  Document Verification
```

2023-09-18 19:05 UTC, vanshg commented on lib/src/main/java/com/smileidentity/models/ProductsConfig.kt
> +data class GlobalDocVResponse(
Can you rename this to `ValidDocumentsResponse`

2023-09-18 19:05 UTC, vanshg commented on lib/src/main/java/com/smileidentity/networking/SmileIDService.kt
> +    suspend fun getGlobalDocVConfig(@Body request: ProductsConfigRequest): GlobalDocVResponse
bump

2023-09-21 09:49 UTC, jumaallan commented on lib/src/main/java/com/smileidentity/compose/document/OrchestratedDocumentVerificationScreen.kt
> +            showSkipButton = false,
Do we want to set it to `false` here explicitly? 

Or should we use the `captureBothSides` flag?

2023-09-21 15:52 UTC, vanshg commented on lib/src/main/java/com/smileidentity/compose/document/OrchestratedDocumentVerificationScreen.kt
> +            showSkipButton = false,
It should be false, since this is for the front of document

2023-09-21 16:12 UTC, jumaallan commented on lib/src/main/java/com/smileidentity/compose/document/OrchestratedDocumentVerificationScreen.kt
> +            showSkipButton = false,
And the back side? Thats set to true by default

The comment was for the two sides actually (Front and Back)

2023-09-21 16:38 UTC, vanshg commented on lib/src/main/java/com/smileidentity/compose/document/OrchestratedDocumentVerificationScreen.kt
> +            showSkipButton = false,
I don't think so, I see `showSkipButton = captureBothSides,` for the back side

2023-09-21 17:23 UTC, jumaallan commented on lib/src/main/java/com/smileidentity/compose/document/OrchestratedDocumentVerificationScreen.kt
> +            showSkipButton = false,
I actually didn't see that 😆

2023-09-21 23:08 UTC, vanshg approved these changes

2023-09-21 23:08 UTC, merged