BVN Consent Screen
smileidentity/android pull request #204
Opened 2023-08-25 12:43 UTC by jumaallan

Story: https://app.shortcut.com/smileid/story/9096/add-bvn-custom-consent-screens-to-the-v10-android-sdk

## Summary

Verifies the NIBSS BVN  via OTP sent to users directly by NIBSS

## Known Issues

Any shortcomings in your work. This may include corner cases not correctly handled or issues related
to but not within the scope of your PR. Design compromises should be discussed here if they were not
already discussed above.

## Test Instructions

Concise test instructions on how to verify that your feature works as intended. This should include
changes to the development environment (if applicable) and all commands needed to run your work.

## Screenshot

If applicable (e.g. UI changes), add screenshots to help explain your work.

2023-08-29 18:23 UTC, vanshg requested changes

2023-08-29 18:23 UTC, vanshg commented on lib/src/main/java/com/smileidentity/compose/components/ContactMethodItem.kt
> +        // ContactMethodItem()
Uncomment?

2023-08-29 18:23 UTC, vanshg commented on lib/src/main/java/com/smileidentity/compose/components/LoadingIndicatorButton.kt
> +    loading: Boolean = false,
Does it make sense to consolidate these two and just pass in `loading`?

enabled can just be !loading? Or do you see a case where we want enabled = loading?

2023-08-29 18:23 UTC, vanshg commented on lib/src/main/java/com/smileidentity/compose/consent/ConsentDeniedScreen.kt
> +internal fun ConsentDeniedScreenPreview() {
Why are we changing the visibility of the Previews?

2023-08-29 18:23 UTC, vanshg commented on lib/src/main/java/com/smileidentity/compose/consent/ConsentScreen.kt
> +internal fun ConsentScreenPreview() {
same here?

2023-08-29 18:23 UTC, vanshg commented on lib/src/main/java/com/smileidentity/compose/consent/bvn/BvnInputScreen.kt
> +    val uiState = viewModel.uiState.collectAsStateWithLifecycle().value
nit:

```suggestion
    val uiState by viewModel.uiState.collectAsStateWithLifecycle()
```

2023-08-29 18:23 UTC, vanshg commented on lib/src/main/java/com/smileidentity/compose/consent/bvn/BvnInputScreen.kt
> +internal fun BvnInputScreenPreview() {
should be private
```suggestion
private fun BvnInputScreenPreview() {
```

2023-08-29 18:23 UTC, vanshg commented on lib/src/main/java/com/smileidentity/compose/consent/bvn/ChooseOtpDeliveryScreen.kt
> +    val uiState = viewModel.uiState.collectAsStateWithLifecycle().value
nit:
```suggestion
    val uiState by viewModel.uiState.collectAsStateWithLifecycle()
```

2023-08-29 18:23 UTC, vanshg commented on lib/src/main/java/com/smileidentity/compose/consent/bvn/OrchestratedBvnConsentScreen.kt
> +    val uiState = viewModel.uiState.collectAsStateWithLifecycle().value
nit:
```suggestion
    val uiState by viewModel.uiState.collectAsStateWithLifecycle()
```

2023-08-29 18:23 UTC, vanshg commented on lib/src/main/java/com/smileidentity/compose/consent/bvn/ShowVerifyOtpScreen.kt
> +    val uiState = viewModel.uiState.collectAsStateWithLifecycle().value
```suggestion
    val uiState by viewModel.uiState.collectAsStateWithLifecycle()
```

2023-08-29 18:23 UTC, vanshg commented on lib/src/main/java/com/smileidentity/models/Bvn.kt
> +data class BvnToptRequest(
nit: typo

Should be "OTP", not "OPT"
```suggestion
data class BvnTotpRequest(
```

2023-08-29 18:23 UTC, vanshg commented on lib/src/main/java/com/smileidentity/models/Bvn.kt
> +data class BvnToptResponse(
opt -> otp

2023-08-29 18:23 UTC, vanshg commented on lib/src/main/java/com/smileidentity/models/Bvn.kt
> +data class BvnToptModeRequest(
same here

2023-08-29 18:23 UTC, vanshg commented on lib/src/main/java/com/smileidentity/models/Bvn.kt
> +data class BvnToptModeResponse(
same here

2023-08-29 18:23 UTC, vanshg commented on lib/src/main/java/com/smileidentity/models/Bvn.kt
> +data class SubmitBvnToptRequest(
same here

2023-08-29 18:23 UTC, vanshg commented on lib/src/main/java/com/smileidentity/models/Bvn.kt
> +data class SubmitBvnToptResponse(
same here

2023-08-29 18:23 UTC, vanshg commented on lib/src/main/java/com/smileidentity/util/Util.kt
> +internal fun createBvnOtpVerificationModes(maps: List<Map<String, String>>):
Can you use the typealias you created? `BvnVerificationMode`

2023-08-29 18:23 UTC, vanshg commented on lib/src/main/java/com/smileidentity/util/Util.kt
> +internal fun createBvnOtpVerificationModes(maps: List<Map<String, String>>):
Use the `typealias` you created?
```suggestion
internal fun createBvnOtpVerificationModes(maps: List<BvnVerificationMode>):
```

2023-08-29 18:23 UTC, vanshg commented on lib/src/main/java/com/smileidentity/viewmodel/BvnConsentViewModel.kt
> +        private set
Why are these mutuableStateOf inside a viewmodel?

2023-08-29 18:23 UTC, vanshg commented on lib/src/main/java/com/smileidentity/viewmodel/BvnConsentViewModel.kt
> +                jobType = JobType.BVN, // TODO - What JobType?
Remove TODO

2023-08-29 18:23 UTC, vanshg commented on lib/src/main/java/com/smileidentity/viewmodel/BvnConsentViewModel.kt
> +                jobType = JobType.BVN, // TODO - What JobType?
ditto

2023-08-29 18:23 UTC, vanshg commented on sample/src/main/java/com/smileidentity/sample/compose/jobs/JobsListScreen.kt
> +                BVN -> com.smileidentity.sample.R.drawable.biometric_kyc
Wrong string resource

2023-08-30 14:22 UTC, jumaallan commented on lib/src/main/java/com/smileidentity/compose/components/ContactMethodItem.kt
> +        // ContactMethodItem()
Fixed

2023-08-30 14:25 UTC, jumaallan commented on lib/src/main/java/com/smileidentity/compose/components/LoadingIndicatorButton.kt
> +    loading: Boolean = false,
Yeah, good catch

2023-08-30 14:27 UTC, jumaallan commented on lib/src/main/java/com/smileidentity/compose/consent/ConsentDeniedScreen.kt
> +internal fun ConsentDeniedScreenPreview() {
Not sure why I even changed the previews from private. Reverted all changes

2023-08-30 14:33 UTC, jumaallan commented on sample/src/main/java/com/smileidentity/sample/compose/jobs/JobsListScreen.kt
> +                BVN -> com.smileidentity.sample.R.drawable.biometric_kyc
I re-used the same drawable as enhanced kyc. to test bvn flow

Let me ask Kwame for a drawable to replace this with

2023-08-30 14:34 UTC, jumaallan commented on lib/src/main/java/com/smileidentity/viewmodel/BvnConsentViewModel.kt
> +        private set
Let me start a small thread on Slack

2023-08-30 18:28 UTC, vanshg commented on lib/src/main/java/com/smileidentity/compose/components/LoadingIndicatorButton.kt
>              if (loading) {
```suggestion
            } else {
```

2023-08-30 18:28 UTC, vanshg commented on lib/src/main/java/com/smileidentity/compose/components/LoadingIndicatorButton.kt
> +fun LoadingButton(
If this can't be marked `internal`, can you mark it with `@SmileIDOptIn`?

2023-08-30 18:28 UTC, vanshg commented on lib/src/main/java/com/smileidentity/compose/consent/bvn/OrchestratedBvnConsentScreen.kt
> +        BvnConsentScreens.BvnInputScreen -> BvnInputScreen(cancelBvnVerification = { /*TODO*/ })
Unaddressed TODO

2023-08-30 18:28 UTC, vanshg commented on lib/src/main/java/com/smileidentity/compose/components/LoadingIndicatorButton.kt
The filename (LoadingIndicatorButton) doesn't match the Composable name (LoadingButton)

2023-08-31 16:27 UTC, jumaallan commented on lib/src/main/java/com/smileidentity/compose/components/LoadingIndicatorButton.kt
>              if (loading) {
Fixed, missed this

2023-08-31 16:32 UTC, jumaallan commented on lib/src/main/java/com/smileidentity/viewmodel/BvnConsentViewModel.kt
> +        private set
We agreed to leave this as is, on the call yesterday - so I did not make this change

2023-08-31 16:33 UTC, jumaallan commented on sample/src/main/java/com/smileidentity/sample/compose/jobs/JobsListScreen.kt
> +                BVN -> com.smileidentity.sample.R.drawable.biometric_kyc
Just pinged Kwame - he says we can re-use this drawable, as it represents government id(s)

2023-08-31 16:40 UTC, vanshg commented on sample/src/main/java/com/smileidentity/sample/compose/jobs/JobsListScreen.kt
> +                BVN -> com.smileidentity.sample.R.drawable.biometric_kyc
Sounds good

2023-08-31 16:41 UTC, vanshg commented on lib/src/main/java/com/smileidentity/viewmodel/BvnConsentViewModel.kt
> +        private set
Sounds good

2023-08-31 16:41 UTC, jumaallan commented on lib/src/main/java/com/smileidentity/compose/consent/bvn/ChooseOtpDeliveryScreen.kt
> +    val uiState = viewModel.uiState.collectAsStateWithLifecycle().value
Fixed

2023-08-31 16:41 UTC, jumaallan commented on lib/src/main/java/com/smileidentity/compose/consent/bvn/OrchestratedBvnConsentScreen.kt
> +    val uiState = viewModel.uiState.collectAsStateWithLifecycle().value
Fixed

2023-08-31 16:41 UTC, jumaallan commented on lib/src/main/java/com/smileidentity/compose/consent/bvn/ShowVerifyOtpScreen.kt
> +    val uiState = viewModel.uiState.collectAsStateWithLifecycle().value
FIxed

2023-08-31 16:41 UTC, jumaallan commented on lib/src/main/java/com/smileidentity/models/Bvn.kt
> +data class BvnToptRequest(
Fixed

2023-08-31 16:42 UTC, jumaallan commented on lib/src/main/java/com/smileidentity/models/Bvn.kt
> +data class BvnToptModeRequest(
Fixed

2023-08-31 16:42 UTC, jumaallan commented on lib/src/main/java/com/smileidentity/models/Bvn.kt
> +data class BvnToptModeResponse(
Fixed

2023-08-31 16:42 UTC, jumaallan commented on lib/src/main/java/com/smileidentity/models/Bvn.kt
> +data class SubmitBvnToptRequest(
Fixed

2023-08-31 16:43 UTC, jumaallan commented on lib/src/main/java/com/smileidentity/models/Bvn.kt
> +data class SubmitBvnToptResponse(
Fixed

2023-08-31 18:38 UTC, vanshg commented
Some UI Notes after testing:

- On the `Select Contact Method` screen, it lets you click Continue before you've made a selection (This might mean you have to revert the change I had previously suggested about coupling the loading and enabled states) 
  - If so, then on the first page for BVN entry, we should disable the Continue button until 11 digits have been entered.
- On the OTP Verification page, the keyboard hides the Continue button. You should look into `Modifier.imePadding()` and `Modifier.imeNestedScroll()` to change the location of the button depending on whether the keyboard is shown
- On the OTP Verification page, clicking the "Enter" button the keyboard currently doesn't do anything. It should submit the BVN
- Entering an incorrect OTP fails silently. We should display some sort of message (toast or snackbar or error on the input field)
- The `OTP Verification` header top margin does not match the top margin of header from the previous screen

2023-09-05 14:44 UTC, vanshg commented on lib/src/main/java/com/smileidentity/compose/consent/bvn/ChooseOtpDeliveryScreen.kt
> +    var canRequestBvnTopt by rememberSaveable { mutableStateOf(false) }
"opt" -> "otp"

2023-09-05 14:44 UTC, vanshg commented on lib/src/main/java/com/smileidentity/compose/consent/bvn/ShowVerifyOtpScreen.kt
> +    var bvnTopt by remember { mutableStateOf("") }
naming: "opt" -> "otp"

2023-09-05 14:44 UTC, vanshg commented on lib/src/main/java/com/smileidentity/compose/consent/bvn/ShowVerifyOtpScreen.kt
> +    if (uiState.showSuccess) successfulBvnVerification.invoke()
```suggestion
    if (uiState.showSuccess) successfulBvnVerification()
```

2023-09-05 14:44 UTC, vanshg commented on lib/src/main/java/com/smileidentity/compose/consent/bvn/ShowVerifyOtpScreen.kt
> +    val uiState = viewModel.uiState.collectAsStateWithLifecycle().value
I don't think this got updated, along with a couple other instances

2023-09-05 14:44 UTC, vanshg commented on lib/src/main/java/com/smileidentity/compose/consent/bvn/ShowVerifyOtpScreen.kt
> +                onClick = { viewModel.submitBvnOtp() },
```suggestion
                onClick = viewModel::submitBvnOtp,
```

2023-09-05 14:44 UTC, vanshg commented on lib/src/main/java/com/smileidentity/viewmodel/BvnConsentViewModel.kt
> +                userId = randomUserId(),
This should be passed in from the external `SmileID.BvnConsentScreen` interface

2023-09-05 15:35 UTC, jumaallan commented on lib/src/main/java/com/smileidentity/viewmodel/BvnConsentViewModel.kt
> +                userId = randomUserId(),
Fixed

2023-09-06 16:31 UTC, vanshg commented on lib/src/main/res/values/strings.xml
> +    <string name="si_bvn_verification_didnt_receive_otp_at">Didn\'t receive the OTP at %1$s ?</string>
nit: spacing
```suggestion
    <string name="si_bvn_verification_didnt_receive_otp_at">Didn\'t receive the OTP at %1$s?</string>
```

2023-09-06 16:31 UTC, vanshg commented on lib/src/main/java/com/smileidentity/compose/consent/bvn/ShowVerifyOtpScreen.kt
>                      },
We should avoid using UI State for business logic. We should instead do something like

```kotlin
onDone = viewModel::onSubmitBvnOtp,
```

and perform the validations inside onSubmitBvnOtp

2023-09-06 16:31 UTC, vanshg commented on lib/src/main/java/com/smileidentity/compose/consent/bvn/ShowVerifyOtpScreen.kt
> +                    if (it.length <= bvnOtpLength) viewModel.updateOtp(it)
See my comment below about moving logic to viewmodel

2023-09-06 16:31 UTC, vanshg commented on lib/src/main/java/com/smileidentity/compose/consent/bvn/BvnInputScreen.kt
> +                if (it.length <= bvnNumberLength) viewModel.updateBvnNumber(it)
See my comment below about moving logic inside viewmodel

2023-09-06 16:31 UTC, vanshg commented on lib/src/main/java/com/smileidentity/compose/SmileIDExt.kt
>      successfulBvnVerification: () -> Unit,
Sorry for not noting this before -- Can we rename this to onSuccessfulBvnVerification? And also move it to the last parameter, so that it can be written as a trailing lambda?

2023-09-07 18:18 UTC, vanshg approved these changes

2023-09-09 11:30 UTC, merged