Set Config via QR Code
smileidentity/android pull request #209
Opened 2023-08-30 15:58 UTC by jumaallan

Story: https://app.shortcut.com/smileid/story/10311/set-partner-config-via-qr-code-on-sample-app

## Summary

Allow partners to scan QR code from portal and fill in the smile config automatically

## Known Issues

Any shortcomings in your work. This may include corner cases not correctly handled or issues related
to but not within the scope of your PR. Design compromises should be discussed here if they were not
already discussed above.

## Test Instructions

Concise test instructions on how to verify that your feature works as intended. This should include
changes to the development environment (if applicable) and all commands needed to run your work.

## Screenshot

If applicable (e.g. UI changes), add screenshots to help explain your work.

2023-08-30 18:31 UTC, vanshg commented on sample/src/main/java/com/smileidentity/sample/compose/components/SmileConfigModalBottomSheet.kt
> +    val scanner = GmsBarcodeScanning.getClient(context)
Does this need to be wrapped in a `remember`? Something like
```suggestion
    val scanner by remember(context) { GmsBarcodeScanning.getClient(context) }
```

2023-08-30 18:32 UTC, vanshg commented on sample/src/main/java/com/smileidentity/sample/compose/components/SmileConfigModalBottomSheet.kt
> +            Button(
Can we make this in-line with the save config button below? And make it an OutlinedButton to delineate it from the Save button

2023-08-30 18:33 UTC, vanshg commented on sample/src/main/java/com/smileidentity/sample/compose/components/SmileConfigModalBottomSheet.kt
> +                Text(text = stringResource(id = R.string.scan_qr_code))
not necessary, but would be a nice touch to include a small QR code logo as well

2023-08-31 16:31 UTC, vanshg requested changes

2023-08-31 16:31 UTC, vanshg commented on sample/sample.gradle.kts
> +    // QR Scanner
nit: i think we could do without this comment
```suggestion
```

2023-08-31 16:31 UTC, vanshg commented on gradle/libs.versions.toml
> +qr-code-scanner = "16.1.0"
2 things:
- can we rename this to `mlkit-code-scanner`? (this is to keep the same convention as the mlkit dependency that was added [here](https://github.com/smileidentity/android/pull/208/files#diff-697f70cdd88ba88fe77eebda60c7e143f6ad1286bca75017421e93ad84fb87dfR31))
- Can you move this to be at the right place in this alphabetical list?

2023-08-31 16:31 UTC, vanshg commented on gradle/libs.versions.toml
> +qr-code-scanner = { module = "com.google.android.gms:play-services-code-scanner", version.ref = "qr-code-scanner"}
ditto

2023-08-31 16:31 UTC, vanshg commented on sample/src/main/AndroidManifest.xml
> +                tools:replace="android:value"/>
Can you add a comment about why we needed to add `tools:replace`?

2023-08-31 17:45 UTC, jumaallan commented on sample/src/main/java/com/smileidentity/sample/compose/components/SmileConfigModalBottomSheet.kt
> +    val scanner = remember(context) { GmsBarcodeScanning.getClient(context) }
I don't think so, unless I missed something

The builder is where we set the options

2023-08-31 17:47 UTC, vanshg commented on sample/src/main/java/com/smileidentity/sample/compose/components/SmileConfigModalBottomSheet.kt
> +    val scanner = remember(context) { GmsBarcodeScanning.getClient(context) }
Looking at step 2:

```kotlin
val scanner = GmsBarcodeScanning.getClient(this)
// Or with a configured options
// val scanner = GmsBarcodeScanning.getClient(this, options)
```

2023-08-31 17:47 UTC, vanshg commented on sample/src/main/java/com/smileidentity/sample/SmileIDApplication.kt
> +        GmsBarcodeScannerOptions.Builder()
This doesn't need to be done at the application's onCreate. It needs to be done when creating the client in the bottom sheet

2023-08-31 17:48 UTC, vanshg commented on gradle/libs.versions.toml
> +mlkit-code-scanner = "16.1.0"
This should go after `maven-publish`

2023-08-31 18:12 UTC, vanshg commented
I just tried this in landscape mode, and the QR code button gets cut off. 2 things we can do to fix -- reduce inter-component spacing to 4 or 8 dp. And add vertical scroll to the column

(pro-tip, you can use the `verticalArrangement=spaceBy` so you don't need to stick `Spacer`s between components everywhere)

```kotlin
Column(
            modifier = Modifier
                .fillMaxWidth()
                .verticalScroll(rememberScrollState())
                .padding(16.dp),
            horizontalAlignment = Alignment.CenterHorizontally,
            verticalArrangement = Arrangement.spacedBy(8.dp),
        )
```

2023-08-31 18:33 UTC, jumaallan commented
> ou don't need to stick `Spacer`s between components everywhere)

That will force us to have same spacing between compoenents, but we already do 16.dp anyway. Let me push a quick fix for that

2023-08-31 18:41 UTC, vanshg approved these changes

2023-09-01 09:36 UTC, merged