UI tweaks (Splash screen & QR code) to first-timer run of sample App
smileidentity/android pull request #267
Opened 2023-11-29 13:38 UTC by jumaallan

Story: https://app.shortcut.com/smileid/story/10931/

## Summary

UI tweaks (Splash screen & QR code) to first-timer run of sample App

## Known Issues

Any shortcomings in your work. This may include corner cases not correctly handled or issues related
to but not within the scope of your PR. Design compromises should be discussed here if they were not
already discussed above.

## Test Instructions

Concise test instructions on how to verify that your feature works as intended. This should include
changes to the development environment (if applicable) and all commands needed to run your work.

## Screenshot

If applicable (e.g. UI changes), add screenshots to help explain your work.

2023-11-29 13:38 UTC, jumaallan commented
Samuel is working on a lottie file to animate the Smile Logo

2023-12-06 22:34 UTC, vanshg requested changes
When I launch the app, I always see the config entry screen momentarily, even though I've already defined the config. This shouldn't happen

2023-12-06 22:34 UTC, vanshg commented on sample/src/main/res/values/strings.xml
> +    <string name="root_config_added_welcome">Welcome partner_%1$s, you can now proceed to the home screen of the Sample App</string>
```suggestion
    <string name="root_config_added_welcome">Welcome Partner %1$s, you can now proceed to the home screen of the Sample App</string>
```

2023-12-06 22:34 UTC, vanshg commented on sample/src/main/java/com/smileidentity/sample/compose/components/SmileConfigModalBottomSheet.kt
> -            OutlinedButton(
Why are we removing the ability to scan QR code from settings?

2023-12-06 22:34 UTC, vanshg commented on sample/src/main/java/com/smileidentity/sample/compose/RootScreen.kt
> +    Scaffold(
Why are we adding a Scaffold here? MainScreen already has a Scaffold

2023-12-06 22:34 UTC, vanshg commented on sample/src/main/java/com/smileidentity/sample/compose/RootScreen.kt
> +        BottomPinnedColumn(
Bump on my previous comment -- can you pull out the smile config entry into its own composable, outside of the RootScreen?

2023-12-08 09:37 UTC, jumaallan commented on sample/src/main/java/com/smileidentity/sample/compose/components/SmileConfigModalBottomSheet.kt
> -            OutlinedButton(
Has been removed on the new design - so it is an option on the main screen

2023-12-13 18:49 UTC, vanshg approved these changes

2023-12-13 18:52 UTC, merged