Trigger Release on Flutter and React Native
smileidentity/android pull request #279
Opened 2023-12-15 12:15 UTC by jumaallan

Story: https://app.shortcut.com/smileid/story/xxx

## Summary

Trigger Release on Flutter and React Native

## Known Issues

Any shortcomings in your work. This may include corner cases not correctly handled or issues related
to but not within the scope of your PR. Design compromises should be discussed here if they were not
already discussed above.

## Test Instructions

Concise test instructions on how to verify that your feature works as intended. This should include
changes to the development environment (if applicable) and all commands needed to run your work.

## Screenshot

If applicable (e.g. UI changes), add screenshots to help explain your work.

2023-12-18 23:16 UTC, vanshg requested changes

2023-12-18 23:16 UTC, vanshg commented on .github/workflows/release.yml
> +            --data '{"ref": "main","inputs": {"android_release_version": "${{ github.event.release.tag_name }}" }}'
Our tag names contain a `v` in the front. You may need to add a step before this to strip the first character

2023-12-19 15:28 UTC, jumaallan commented on .github/workflows/release.yml
> +            --data '{"ref": "main","inputs": {"android_release_version": "${{ github.event.release.tag_name }}" }}'
We atrip that in the flutter and react native repo

2023-12-19 21:49 UTC, vanshg commented on .github/workflows/release.yml
> +            --data '{"ref": "main","inputs": {"android_release_version": "${{ github.event.release.tag_name }}" }}'
Ah, okay

2023-12-19 21:50 UTC, vanshg approved these changes

2023-12-19 22:43 UTC, merged